import { create } from "zustand";

import { CalendarEvent } from "../types/calendarTypes";

export interface ColorComboType {
  text: string;
}

interface CalendarEventsStore {
  items: CalendarEvent[];
  addItem: (item: CalendarEvent) => void;
  removeItem: (id: number) => void;
  updateItem: (id: number, updatedItem: CalendarEvent) => void;
}

const CalendarEvents: CalendarEvent[] = [
  {
    id: 1,
    title: "Meeting 1",
    desc: "Discuss project updates",
    date: "2023-08-14",
    startTime: "09:00 AM",
    endTime: "10:30 AM",
    height: 90,
    location: "Meeting Room 1",
    type: "CalendarEvent",
  },
  {
    id: 2,
    title: "Lunch",
    desc: "Lunch with colleagues",
    date: "2023-08-14",
    startTime: "12:30 PM",
    endTime: "01:30 PM",
    height: 60,
    location: "Cafeteria",
    type: "CalendarEvent",
  },
  {
    id: 3,
    title: "Workshop",
    desc: "Team workshop on new tools",
    date: "2023-08-14",
    startTime: "02:00 PM",
    endTime: "04:00 PM",
    height: 120,
    location: "Conference Room B",
    type: "CalendarEvent",
  },
  {
    id: 4,
    title: "Team Huddle",
    desc: "Quick team huddle",
    date: "2023-08-15",
    startTime: "04:30 PM",
    endTime: "05:00 PM",
    height: 30,
    location: "Team Area",
    type: "CalendarEvent",
  },
  {
    id: 5,
    title: "Training Session",
    desc: "Training on new software",
    date: "2023-08-15",
    startTime: "09:30 AM",
    endTime: "12:00 PM",
    height: 150,
    location: "Training Room 2",
    type: "CalendarEvent",
  },
  {
    id: 6,
    title: "Client Call",
    desc: "Call with important client",
    date: "2023-08-16",
    startTime: "03:00 PM",
    endTime: "03:45 PM",
    height: 45,
    location: "Online",
    type: "CalendarEvent",
  },
  {
    id: 7,
    title: "Team Building Activity",
    desc: "Outdoor team building event",
    date: "2023-08-16",
    startTime: "11:00 AM",
    endTime: "02:00 PM",
    height: 180,
    location: "Outdoor Area",
    type: "CalendarEvent",
  },
  {
    id: 8,
    title: "Project Discussion",
    desc: "Discussing new project proposal",
    date: "2023-08-16",
    startTime: "05:30 PM",
    endTime: "06:30 PM",
    height: 60,
    location: "Meeting Room 3",
    type: "CalendarEvent",
  },
  {
    id: 9,
    title: "Breakfast Meeting",
    desc: "Meeting with business partners",
    date: "2023-08-16",
    startTime: "07:00 AM",
    endTime: "09:00 AM",
    height: 60,
    location: "Restaurant",
    type: "CalendarEvent",
  },
  {
    id: 10,
    title: "Product Demo",
    desc: "Demo of new product features",
    date: "2023-08-17",
    startTime: "02:30 PM",
    endTime: "03:30 PM",
    height: 60,
    location: "Showroom",
    type: "CalendarEvent",
  },
  {
    id: 11,
    title: "Meeting 2",
    desc: "Discuss project updates",
    date: "2023-08-17",
    startTime: "11:00 AM",
    endTime: "12:00 PM",
    height: 60,
    location: "Meeting Room 4",
    type: "CalendarEvent",
  },
  {
    id: 12,
    title: "Coffee Break",
    desc: "Coffee break with team",
    date: "2023-08-18",
    startTime: "10:30 AM",
    endTime: "10:45 AM",
    height: 15,
    location: "Break Room",
    type: "CalendarEvent",
  },
  {
    id: 13,
    title: "Presentation",
    desc: "Presenting sales strategies",
    date: "2023-08-18",
    startTime: "01:00 PM",
    endTime: "02:00 PM",
    height: 60,
    location: "Conference Room A",
    type: "CalendarEvent",
  },
  {
    id: 14,
    title: "Team Lunch",
    desc: "Lunch with the whole team",
    date: "2023-08-18",
    startTime: "12:00 PM",
    endTime: "01:00 PM",
    height: 60,
    location: "Cafeteria",
    type: "CalendarEvent",
  },
  {
    id: 15,
    title: "Design Review",
    desc: "Reviewing new design concepts",
    date: "2023-08-19",
    startTime: "03:45 PM",
    endTime: "04:45 PM",
    height: 60,
    location: "Design Studio",
    type: "CalendarEvent",
  },
  {
    id: 16,
    title: "Brainstorming Session",
    desc: "Generating new ideas",
    date: "2023-08-19",
    startTime: "01:30 PM",
    endTime: "02:30 PM",
    height: 60,
    location: "Meeting Room 5",
    type: "CalendarEvent",
  },
  {
    id: 17,
    title: "Client Meeting",
    desc: "Meeting with potential client",
    date: "2023-08-19",
    startTime: "04:00 PM",
    endTime: "05:00 PM",
    height: 60,
    location: "Client Office",
    type: "CalendarEvent",
  },
  {
    id: 18,
    title: "Internal Presentation",
    desc: "Presenting quarterly results",
    date: "2023-07-29",
    startTime: "05:30 PM",
    endTime: "06:30 PM",
    height: 60,
    location: "Conference Room C",
    type: "CalendarEvent",
  },
  {
    id: 19,
    title: "Coding Session",
    desc: "Collaborative coding session",
    date: "2023-07-29",
    startTime: "02:00 PM",
    endTime: "03:00 PM",
    height: 60,
    location: "Meeting Room 6",
    type: "CalendarEvent",
  },
  {
    id: 20,
    title: "Team Celebration",
    desc: "Celebrating successful project",
    date: "2023-07-29",
    startTime: "06:45 PM",
    endTime: "08:00 PM",
    height: 75,
    location: "Party Room",
    type: "CalendarEvent",
  },
  {
    id: 21,
    title: "Meeting 1",
    desc: "Discuss project updates",
    date: "2023-07-31",
    startTime: "09:00 AM",
    endTime: "10:30 AM",
    height: 90,
    location: "Meeting Room 1",
    type: "CalendarEvent",
  },
  {
    id: 22,
    title: "Lunch",
    desc: "Lunch with colleagues",
    date: "2023-07-31",
    startTime: "12:30 PM",
    endTime: "01:30 PM",
    height: 60,
    location: "Cafeteria",
    type: "CalendarEvent",
  },
  {
    id: 23,
    title: "Workshop",
    desc: "Team workshop on new tools",
    date: "2023-07-31",
    startTime: "02:00 PM",
    endTime: "04:00 PM",
    height: 120,
    location: "Conference Room B",
    type: "CalendarEvent",
  },
  {
    id: 24,
    title: "Team Huddle",
    desc: "Quick team huddle",
    date: "2023-08-01",
    startTime: "04:30 PM",
    endTime: "05:00 PM",
    height: 30,
    location: "Team Area",
    type: "CalendarEvent",
  },
  {
    id: 25,
    title: "Training Session",
    desc: "Training on new software",
    date: "2023-08-01",
    startTime: "09:30 AM",
    endTime: "12:00 PM",
    height: 150,
    location: "Training Room 2",
    type: "CalendarEvent",
  },
  {
    id: 26,
    title: "Client Call",
    desc: "Call with important client",
    date: "2023-08-02",
    startTime: "03:00 PM",
    endTime: "03:45 PM",
    height: 45,
    location: "Online",
    type: "CalendarEvent",
  },
  {
    id: 27,
    title: "Team Building Activity",
    desc: "Outdoor team building event",
    date: "2023-08-02",
    startTime: "11:00 AM",
    endTime: "02:00 PM",
    height: 180,
    location: "Outdoor Area",
    type: "CalendarEvent",
  },
  {
    id: 28,
    title: "Project Discussion",
    desc: "Discussing new project proposal",
    date: "2023-08-02",
    startTime: "05:30 PM",
    endTime: "06:30 PM",
    height: 60,
    location: "Meeting Room 3",
    type: "CalendarEvent",
  },
  {
    id: 29,
    title: "Breakfast Meeting",
    desc: "Meeting with business partners",
    date: "2023-08-02",
    startTime: "08:00 AM",
    endTime: "09:00 AM",
    height: 60,
    location: "Restaurant",
    type: "CalendarEvent",
  },
  {
    id: 30,
    title: "Product Demo",
    desc: "Demo of new product features",
    date: "2023-08-03",
    startTime: "02:30 PM",
    endTime: "03:30 PM",
    height: 60,
    location: "Showroom",
    type: "CalendarEvent",
  },
  {
    id: 31,
    title: "Meeting 2",
    desc: "Discuss project updates",
    date: "2023-08-03",
    startTime: "11:00 AM",
    endTime: "12:00 PM",
    height: 60,
    location: "Meeting Room 4",
    type: "CalendarEvent",
  },
  {
    id: 32,
    title: "Coffee Break",
    desc: "Coffee break with team",
    date: "2023-08-04",
    startTime: "10:30 AM",
    endTime: "10:45 AM",
    height: 15,
    location: "Break Room",
    type: "CalendarEvent",
  },
  {
    id: 33,
    title: "Presentation",
    desc: "Presenting sales strategies",
    date: "2023-08-04",
    startTime: "01:00 PM",
    endTime: "02:00 PM",
    height: 60,
    location: "Conference Room A",
    type: "CalendarEvent",
  },
  {
    id: 34,
    title: "Team Lunch",
    desc: "Lunch with the whole team",
    date: "2023-08-04",
    startTime: "12:00 PM",
    endTime: "01:00 PM",
    height: 60,
    location: "Cafeteria",
    type: "CalendarEvent",
  },
  {
    id: 35,
    title: "Design Review",
    desc: "Reviewing new design concepts",
    date: "2023-08-05",
    startTime: "03:45 PM",
    endTime: "04:45 PM",
    height: 60,
    location: "Design Studio",
    type: "CalendarEvent",
  },
  {
    id: 36,
    title: "Brainstorming Session",
    desc: "Generating new ideas",
    date: "2023-08-05",
    startTime: "01:30 PM",
    endTime: "02:30 PM",
    height: 60,
    location: "Meeting Room 5",
    type: "CalendarEvent",
  },
  {
    id: 37,
    title: "Client Meeting",
    desc: "Meeting with potential client",
    date: "2023-08-05",
    startTime: "04:00 PM",
    endTime: "05:00 PM",
    height: 60,
    location: "Client Office",
    type: "CalendarEvent",
  },
  {
    id: 38,
    title: "Internal Presentation",
    desc: "Presenting quarterly results",
    date: "2023-08-06",
    startTime: "05:30 PM",
    endTime: "06:30 PM",
    height: 60,
    location: "Conference Room C",
    type: "CalendarEvent",
  },
  {
    id: 39,
    title: "Coding Session",
    desc: "Collaborative coding session",
    date: "2023-08-06",
    startTime: "02:00 PM",
    endTime: "03:00 PM",
    height: 60,
    location: "Meeting Room 6",
    type: "CalendarEvent",
  },
  {
    id: 40,
    title: "Team Celebration",
    desc: "Celebrating successful project",
    date: "2023-08-06",
    startTime: "06:45 PM",
    endTime: "08:00 PM",
    height: 75,
    location: "Party Room",
    type: "CalendarEvent",
  },
];

const useCalendarState = create<CalendarEventsStore>(set => ({
  items: CalendarEvents,
  addItem: (item: CalendarEvent) =>
    set((state: CalendarEventsStore) => ({
      items: [...state.items, item],
    })),
  removeItem: (id: number) =>
    set((state: CalendarEventsStore) => ({
      items: state.items.filter(item => item.id !== id),
    })),
  updateItem: (id: number, updatedItem: CalendarEvent) =>
    set(state => ({
      items: state.items.map(item =>
        item.id === id ? { ...item, ...updatedItem } : item,
      ),
    })),
}));

export { useCalendarState };
